
package com.cliente.vista;

import com.cliente.bo.ClienteBO;
import com.cliente.identidad.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author FABITH
 */
public class FrmCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmCliente
     */
    private ClienteBO ebo = new ClienteBO();
    
    public FrmCliente() {
        initComponents();
        listarCliente();
        idMax();
        setTitle("FORMULARIO EMPLEADO");
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void listarCliente(){
        ebo.listarCliente(tbCliente);
    }
//    private ClienteBO ebo = new ClienteBO();
//    public void listarCliente(){
//        ebo.listarCliente(tbCliente);
//    }
    
    public void idMax(){
        txtClienteId.setText(ebo.getMaxId()+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbClienteFormulario = new javax.swing.JLabel();
        txtClienteId = new javax.swing.JTextField();
        txtClienteApellido1 = new javax.swing.JTextField();
        txtClienteNombre2 = new javax.swing.JTextField();
        txtClienteEdad = new javax.swing.JTextField();
        txtClienteApellido2 = new javax.swing.JTextField();
        txtClienteNombre1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtClienteIdentificacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtClienteCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtClienteFijo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtClienteCorreo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtClienteCuenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        btClienteAgregar = new javax.swing.JButton();
        btClienteModificar = new javax.swing.JButton();
        btClienteEliminar = new javax.swing.JButton();
        btClienteLimpiar = new javax.swing.JButton();
        btClienteSalir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtClienteRut = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbClienteFormulario.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbClienteFormulario.setText("FerreserviciosJF CLIENTE");

        txtClienteId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtClienteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteIdActionPerformed(evt);
            }
        });

        txtClienteApellido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteApellido1ActionPerformed(evt);
            }
        });

        txtClienteNombre2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteNombre2ActionPerformed(evt);
            }
        });

        txtClienteEdad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteEdadActionPerformed(evt);
            }
        });

        txtClienteApellido2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteApellido2ActionPerformed(evt);
            }
        });

        txtClienteNombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteNombre1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Primer Nombre:    *");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Segundo Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Primer Apellido:   *");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Segundo Apellido:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Edad:                     *");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("ID:                         *");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Identificacion:      *");

        txtClienteIdentificacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteIdentificacionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Tel Celular:");

        txtClienteCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCelularActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Tel Fijo :                 *");

        txtClienteFijo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteFijoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("Correo :                  *");

        txtClienteCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCorreoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("# Cuenta Bancaria :");

        txtClienteCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCuentaActionPerformed(evt);
            }
        });

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCliente);

        btClienteAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btClienteAgregar.setText("AGREGAR");
        btClienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteAgregarActionPerformed(evt);
            }
        });

        btClienteModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btClienteModificar.setText("MODIFICAR");
        btClienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteModificarActionPerformed(evt);
            }
        });

        btClienteEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btClienteEliminar.setText("ELIMINAR");
        btClienteEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClienteEliminarMouseClicked(evt);
            }
        });
        btClienteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteEliminarActionPerformed(evt);
            }
        });

        btClienteLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btClienteLimpiar.setText("LIMPIAR");
        btClienteLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteLimpiarActionPerformed(evt);
            }
        });

        btClienteSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btClienteSalir.setText("SALIR");
        btClienteSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteSalirActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setText("Rut:");

        txtClienteRut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtClienteRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteRutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtClienteApellido2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(txtClienteApellido1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClienteNombre2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClienteEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClienteCuenta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClienteFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteRut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btClienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btClienteLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btClienteSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbClienteFormulario)
                .addGap(410, 410, 410))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbClienteFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtClienteEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtClienteNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtClienteNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtClienteApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienteApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtClienteRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtClienteIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtClienteFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtClienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtClienteCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btClienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btClienteLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btClienteSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteIdActionPerformed

    private void txtClienteApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteApellido1ActionPerformed

    private void txtClienteNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteNombre2ActionPerformed

    private void txtClienteEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteEdadActionPerformed

    private void txtClienteApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteApellido2ActionPerformed

    private void txtClienteNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteNombre1ActionPerformed

    private void txtClienteIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteIdentificacionActionPerformed

    private void txtClienteCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteCelularActionPerformed

    private void txtClienteFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteFijoActionPerformed

    private void txtClienteCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteCorreoActionPerformed

    private void txtClienteCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteCuentaActionPerformed

    private void btClienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteModificarActionPerformed
        if(txtClienteId.getText().isEmpty() || 
            txtClienteEdad.getText().isEmpty()||
            txtClienteNombre1.getText().isEmpty() ||
            txtClienteApellido1.getText().isEmpty() ||
            txtClienteIdentificacion.getText().isEmpty() ||
            txtClienteFijo.getText().isEmpty() ||
            txtClienteCorreo.getText().isEmpty() 
        ){
            JOptionPane.showMessageDialog(null, "             DIGITE TODOS LOS CAMPOS \n" 
                                            + "TODOS LOS CAMPOS CON * SON OBLIGATORIOS");
        }else{
            Cliente cli = new Cliente();
            cli.setId_cliente(Integer.parseInt(txtClienteId.getText()));
            cli.setEdad_cli(Integer.parseInt(txtClienteEdad.getText()));
            cli.setRut_cli(txtClienteRut.getText());
            cli.setPrimer_nombre_cli(txtClienteNombre1.getText());
            cli.setSegundo_nombre_cli(txtClienteNombre2.getText());
            cli.setPrimer_apellido_cli(txtClienteApellido1.getText());
            cli.setSegundo_apellido_cli(txtClienteApellido2.getText());
            cli.setIdentificacion_cli(txtClienteIdentificacion.getText());
            cli.setTelefono_celular_cli(txtClienteCelular.getText());
            cli.setTelefono_fijo_cli(txtClienteFijo.getText());
            cli.setCorreo_cli(txtClienteCorreo.getText());
            cli.setCuenta_bancaria_cli(txtClienteCuenta.getText());
            String mensaje = ebo.modificarCliente(cli);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarCliente();
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_btClienteModificarActionPerformed

    private void btClienteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteEliminarActionPerformed
        if(txtClienteId.getText().isEmpty() || 
            txtClienteEdad.getText().isEmpty()||
            txtClienteNombre1.getText().isEmpty() ||
            txtClienteApellido1.getText().isEmpty() ||
            txtClienteIdentificacion.getText().isEmpty() ||
            txtClienteFijo.getText().isEmpty() ||
            txtClienteCorreo.getText().isEmpty()
        )
        {
            JOptionPane.showMessageDialog(null, "DIGITE TODOS LOS CAMPOS");
        }else{   
            String mensaje = ebo.eliminarCliente(Integer.parseInt(txtClienteId.getText()));
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarCliente();
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_btClienteEliminarActionPerformed

    private void btClienteLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteLimpiarActionPerformed
        limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btClienteLimpiarActionPerformed
    public void limpiar(){
        txtClienteId.setText("");
        txtClienteEdad.setText("");
        txtClienteRut.setText("");
        txtClienteNombre1.setText("");
        txtClienteNombre2.setText("");
        txtClienteApellido1.setText("");
        txtClienteApellido2.setText("");
        txtClienteIdentificacion.setText("");
        txtClienteCelular.setText("");
        txtClienteFijo.setText("");
        txtClienteCorreo.setText("");
        txtClienteCuenta.setText("");
        idMax();
    }
    private void btClienteSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteSalirActionPerformed
        System.exit(0);       
    }//GEN-LAST:event_btClienteSalirActionPerformed

    private void txtClienteRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteRutActionPerformed

    private void btClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteAgregarActionPerformed
        if(txtClienteId.getText().isEmpty() || 
            txtClienteEdad.getText().isEmpty()||
            txtClienteNombre1.getText().isEmpty() ||
            txtClienteApellido1.getText().isEmpty() ||
            txtClienteIdentificacion.getText().isEmpty() ||
            txtClienteFijo.getText().isEmpty() ||
            txtClienteCorreo.getText().isEmpty()
        ){
            JOptionPane.showMessageDialog(null, "             DIGITE TODOS LOS CAMPOS \n" 
                                            + "TODOS LOS CAMPOS CON * SON OBLIGATORIOS");
        }else{
            Cliente cli = new Cliente();
            cli.setId_cliente(Integer.parseInt(txtClienteId.getText()));
            cli.setEdad_cli(Integer.parseInt(txtClienteEdad.getText()));
            cli.setRut_cli(txtClienteRut.getText());
            cli.setPrimer_nombre_cli(txtClienteNombre1.getText());
            cli.setSegundo_nombre_cli(txtClienteNombre2.getText());
            cli.setPrimer_apellido_cli(txtClienteApellido1.getText());
            cli.setSegundo_apellido_cli(txtClienteApellido2.getText());
            cli.setIdentificacion_cli(txtClienteIdentificacion.getText());
            cli.setTelefono_celular_cli(txtClienteCelular.getText());
            cli.setTelefono_fijo_cli(txtClienteFijo.getText());
            cli.setCorreo_cli(txtClienteCorreo.getText());
            cli.setCuenta_bancaria_cli(txtClienteCuenta.getText());
            String mensaje = ebo.agregarCliente(cli);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarCliente();
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_btClienteAgregarActionPerformed

    private void tbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClienteMouseClicked
        int seleccion = tbCliente.rowAtPoint(evt.getPoint());
        txtClienteId.setText(tbCliente.getValueAt(seleccion, 0) +"");
        txtClienteEdad.setText(tbCliente.getValueAt(seleccion, 1) +"");
        txtClienteRut.setText(tbCliente.getValueAt(seleccion, 2) +"");
        txtClienteNombre1.setText(tbCliente.getValueAt(seleccion, 3) +"");
        txtClienteNombre2.setText(tbCliente.getValueAt(seleccion, 4) +"");
        txtClienteApellido1.setText(tbCliente.getValueAt(seleccion, 5) +"");
        txtClienteApellido2.setText(tbCliente.getValueAt(seleccion, 6) +"");
        txtClienteIdentificacion.setText(tbCliente.getValueAt(seleccion, 7) +"");
        txtClienteCelular.setText(tbCliente.getValueAt(seleccion, 8) +"");
        txtClienteFijo.setText(tbCliente.getValueAt(seleccion, 9) +"");
        txtClienteCorreo.setText(tbCliente.getValueAt(seleccion, 10) +"");
        txtClienteCuenta.setText(tbCliente.getValueAt(seleccion, 11) +"");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tbClienteMouseClicked

    private void btClienteEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClienteEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btClienteEliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClienteAgregar;
    private javax.swing.JButton btClienteEliminar;
    private javax.swing.JButton btClienteLimpiar;
    private javax.swing.JButton btClienteModificar;
    private javax.swing.JButton btClienteSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbClienteFormulario;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTextField txtClienteApellido1;
    private javax.swing.JTextField txtClienteApellido2;
    private javax.swing.JTextField txtClienteCelular;
    private javax.swing.JTextField txtClienteCorreo;
    private javax.swing.JTextField txtClienteCuenta;
    private javax.swing.JTextField txtClienteEdad;
    private javax.swing.JTextField txtClienteFijo;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtClienteIdentificacion;
    private javax.swing.JTextField txtClienteNombre1;
    private javax.swing.JTextField txtClienteNombre2;
    private javax.swing.JTextField txtClienteRut;
    // End of variables declaration//GEN-END:variables
}
